### ISSUE TITLE
有些能转换有些不能转换

### ISSUE THREAD

**Issue by LMXsecound** [ghtz08/kugou-kgm-decoder#4]
![image](https://github.com/user-attachments/assets/75b7bd83-70ea-40ca-b593-28c09991b065)

**Comment by LMXsecound** [comment]
[陶喆 - 今天你要嫁给我_SQ.kgm.zip](https://github.com/user-attachments/files/16750887/-._SQ.kgm.zip)
这个是转换不了的文件，盼复

**Comment by ghtz08** [comment]
这看起来像是一种新的混淆方式，我会在这周末尝试适配，不一定能成功。

**Comment by ghtz08** [comment]
非常抱歉，我参考的[项目 unlock-music](https://git.unlock-music.dev/um/cli)无法解开这个文件，我无法同步这个文件的解密方式。
